### ISSUE TITLE
Token upgrade mechanism is broken [BugBounty]

### ISSUE THREAD

**Issue by k06a** [blockpass-org/smart_contracts#1]
Current implementation of `Pass1.mintTo()` method is broken:
```
function mintTo() 
    hasUpgrade 
    whenPaused
    onlyWhitelisted
    public 
{
    uint256 balance = balanceOf(msg.sender);

    // burn the tokens in this token smart contract
    super.burn(balance);

    // mint tokens in the new token smart contract
    require(newToken.mint(msg.sender, balance)); // <-- Problem is here
    emit LogMint(msg.sender, balance);
}
```

Exactly this line will fail: `require(newToken.mint(msg.sender, balance));`. Because `mint` method can be called only by `owner` (see MintableToken code). But old token smart contract could not be `owner` of new token smart contract for many reasons: a lot of other owner responsibilities.

Next version of token `Pass2` can implement a hack to fix this issue:
```
contract Pass2
{
    address public oldToken;

    constructor(address _oldToken)
        public
    {
        oldToken = _ oldToken;
    }

    function mint(address _to, uint256 _amount)
        //onlyOwner // <-- should be removed
        canMint 
        public 
        returns (bool) 
    {
        if (msg.sender == oldToken) {
            address tmpOwner = owner;
            owner = msg.sender; // <-- Going to trick parent's implementation MintableToken.mint
            bool ret = super.mint(_to, _amount);
            owner = tmpOwner; // <-- Restore original value
            return ret;
        }

        revert();
        return true;
    }
}
```

I think you should develop a more clean solution for Pass3 and next upgrades. But Pass2 most likely will have some kind of hack to fix Pass1 upgrade system bug.

My address for bounty: `0x4fFfbB9905d14794cb18D192e8056C6aa7cbA3C4`

**Comment by thmsl** [comment]
@k06a thanks for submitting this issue.

Here you assume that the new smart contract (PASS 2) will use the same function mint() as PASS1. This won't be the case.
We added in PASS1 onlyOwner and revert() on purpose so this function is never called in PASS1

Obviously the mint() function in PASS2 won't be the same


Function **mint**() in PASS1 that will never be called :
```
    * @dev override from MintableToken
    * @param _to address of receivers
    * _amount amount of token to redeem to
    * @return exception to prevent calling directly to Pass1 token
    */
    function mint(address _to, uint256 _amount) 
        onlyOwner 
        canMint 
        public 
        returns (bool) 
    {
        revert();
        return true;
    }
```
Function **mintTo**() in PASS1 that will call PASS2.mint() :
```
function mintTo() 
    hasUpgrade 
    whenPaused
    onlyWhitelisted
    public 
{
    uint256 balance = balanceOf(msg.sender);

    // burn the tokens in this token smart contract
    super.burn(balance);

    // mint tokens in the new token smart contract
    require(newToken.mint(msg.sender, balance)); 
    emit LogMint(msg.sender, balance);
}
```
PASS2.**mint**() can be something like that for example :
```
    function mint(address _to, uint256 _amount) canMint public returns (bool) {
        totalSupply_ = totalSupply_.add(_amount);
        balances[_to] = balances[_to].add(_amount);
        emit Mint(_to, _amount);
        emit Transfer(address(0), _to, _amount);
        return true;
    }
```

We are appreciating your feedback but we can't consider it a bug as PASS2 does not exist yet.

**Comment by k06a** [comment]
@thmsl ok, missing Pass2 draft makes me think it should be a few changed copy of Pass1. If you introduce upgrade mechanism you should provide at least some drafts of next versions. Hope you understand that provided implementation of `Pass2.mint` is not safe because it could be called by anyone and should be additionally protected.

**Comment by thmsl** [comment]
> if you introduce upgrade mechanism you should provide at least some drafts of next versions.

We don't want to mislead with a draft/incomplete version of a potential upgrade

> Hope you understand that provided implementation of Pass2.mint is not safe because it could be 
called by anyone and should be additionally protected.

When time comes, the new contract will be thoroughly tested and audited.

I am closing this issue. Thanks again for your feedback
